// Generated by Wrangler on Tue May 21 2024 10:26:31 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	POSTS: KVNamespace;
	S3_URL: "https://ck-portfolio-images.s3.eu-west-2.amazonaws.com";
	UNSPLASH_ACCESS_KEY: string;
}
